import { Arintdpk } from './arintdpk';
export class Arintd {
  arintdPK: Arintdpk;
  tipoArti: string;
  indTipoTra: string;
  descri: string;
  movimi: string;
  regMov: string;
  guiaFactura: string;
  docuGene: string;
  ctrolSeriado: string;
  contabiliza: string;
  afectCost: string;
  codDiario: string;
  indKardex: string;
  indControl: string;
  indConsu: string;
  indActuStk: string;
  trasladoAuto: string;
  indTipoConsu: string;
  indActivo: string;
  grupoOri: string;
  almaOri: string;
  grupoDes: string;
  almaDes: string;
  indDevo: string;
  indPedido: string;
  indNotaCred: string;
  indFactura: string;
  indGuia: string;
  entiRefe: string;
  docu1Refe: string;
  docu2Refe: string;
  tipoDepend: string;
  tipoTranComp: string;
  tipoTranReve: string;
  motivoTraslado: string;
  indAjuStock: string;
  activo: string;
  indExportacion: string;
  indVtaAnticipada: string;
  tipoDepend1:string;
  tipoTranAuto: string;
  solPed: string;
  estadoItem: string;
  usuario: string;
  indAjuCero: string;
  soloInvent: string;
  demasia: string;
  indNoObligaCb: string;
  indFactTexto: string;
  indCampana: string;
  ingresaCosteo: string;
  indOperacCosteo: string;
  indGuiaTexto: string;
  indGmprod: string;
  codTransAnt: string;
  convenio: string;
  indColegio: string;
  indFinPublic: string;
  indControlImprenta: string;
  indContadoNeto: string;
  indPrecV: string;
  sinfacbol: string;



}
