import { Arpfol } from './Arpfol';
import { IdArpfoe } from './IdArpfoe';

export class Arpfoe {

  arpfoePK: IdArpfoe;
  grupo: string;
  noCliente: string;
  division: string;
  noVendedor: string;
  codTPed: string;
  codFpago: string;
  fRecepcion: string;
  fechaRegistro: string;
  fAprobacion: string;
  tipoPrecio: string;
  tipoFpago: string;
  moneda: string;
  tipoCambio: number;
  subTotal: number;
  tImpuesto: number;
  tPrecio: number;
  impuesto: number;
  estado: string;
  bodega: string;
  igv: number;
  indGuiado: string;
  noSolic: string;
  observa: string;
  perDeGracia: number;
  direccionComercial: string;
  codiDepa: string;
  codiProv: string;
  codiDist: string;
  motivoTraslado: string;
  nombreCliente: string;
  ruc: string;
  tDescuento: number;
  fechaDocRef: Date;
  tipoDocRef: string;
  codClasPed: string;
  tipoPago: string;
  tDsctoGlobal: number;
  tValorVenta: number;
  codTienda: string;
  nomTienda: string;
  direcTienda: string;
  almaOrigen: string;
  almaDestino: string;
  tipoArti: string;
  tipoDocCli: string;
  numDocCli: string;
  totalBruto: number;
  tipo: string;
  indPvent: string;
  centro: string;
  indFactura1: string;
  indBoleta1: string;
  codCaja: string;
  cajera: string;
  centroCosto: string;
  indNotaCred: string;
  indExportacion: string;
  consumo: string;
  indFerias: string;
  indProvincia: string;
  redondeo: number;
  indCodBarra: string;
  operExoneradas: number;
  operGratuitas: number;
  operGravadas: number;
  operInafectas: number;
  tipoOperacion: string;
  emailPedido: string;
  arpfolList: Arpfol[];

}
