import { Arpffepk } from './arpffepk';
import { Arpffl } from './arpffl';
export class Arpffe {
  arpffePK: Arpffepk;
  fecha: string;
  grupo: string;
  noCliente: string;
  noVendedor: string;
  descripcion: string;
  noOrden: string;
  estado: string;
  tipoDoc: string;
  noFactu: string;
  centro: string;
  tipo: string;
  clase: string;
  noDocu: string;
  tipoTransc: string;
  usuario: string;
  fechaInicio: Date;
  codFpago: string;
  almaOrigen: string;
  almaDestino: string;
  nombreDigi: string;
  indFactura: string;
  indBoleta: string;
  codTienda: string;
  tipoGuia: string;
  imprime: string;
  indPvent: string;
  codCaja: string;
  indFerias: string;
  indProvincia: string;
  consumo: string;
  convenio: string;
  indCodBarra: string;
  indFicta: string;
  indProforma: string;
  arpfflList: Arpffl[];
}
